"""add_phase_9_maintenance_models

Revision ID: 01f9b17d3cb8
Revises: fb30b4bdf118
Create Date: 2026-09-24 15:30:13.399628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f9b17d3cb8'
down_revision: Union[str, None] = 'fb30b4bdf118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('performed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('procedure_performed', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_equipment_id'), 'maintenance_records', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_id'), 'maintenance_records', ['id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_maintenance_type'), 'maintenance_records', ['maintenance_type'], unique=False)
    op.create_index(op.f('ix_maintenance_records_scheduled_date'), 'maintenance_records', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_maintenance_records_status'), 'maintenance_records', ['status'], unique=False)
    op.create_index(op.f('ix_maintenance_records_store_id'), 'maintenance_records', ['store_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_technician_id'), 'maintenance_records', ['technician_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_title'), 'maintenance_records', ['title'], unique=False)
    op.add_column('checklists', sa.Column('maintenance_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_checklists_maintenance_id'), 'checklists', ['maintenance_id'], unique=False)
    op.create_foreign_key(None, 'checklists', 'maintenance_records', ['maintenance_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'checklists', type_='foreignkey')
    op.drop_index(op.f('ix_checklists_maintenance_id'), table_name='checklists')
    op.drop_column('checklists', 'maintenance_id')
    op.drop_index(op.f('ix_maintenance_records_title'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_technician_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_store_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_status'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_scheduled_date'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_maintenance_type'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_equipment_id'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    # ### end Alembic commands ###
