"""add_commands_and_standard_responses_models

Revision ID: 4d6b319bf17a
Revises: 547f5c06cda8
Create Date: 2026-09-24 10:58:10.975703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d6b319bf17a'
down_revision: Union[str, None] = '547f5c06cda8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('system', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('copies_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commands_category'), 'commands', ['category'], unique=False)
    op.create_index(op.f('ix_commands_id'), 'commands', ['id'], unique=False)
    op.create_index(op.f('ix_commands_system'), 'commands', ['system'], unique=False)
    op.create_index(op.f('ix_commands_title'), 'commands', ['title'], unique=False)
    op.create_table('standard_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('audience', sa.String(length=50), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('copies_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standard_responses_audience'), 'standard_responses', ['audience'], unique=False)
    op.create_index(op.f('ix_standard_responses_category'), 'standard_responses', ['category'], unique=False)
    op.create_index(op.f('ix_standard_responses_id'), 'standard_responses', ['id'], unique=False)
    op.create_index(op.f('ix_standard_responses_title'), 'standard_responses', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_standard_responses_title'), table_name='standard_responses')
    op.drop_index(op.f('ix_standard_responses_id'), table_name='standard_responses')
    op.drop_index(op.f('ix_standard_responses_category'), table_name='standard_responses')
    op.drop_index(op.f('ix_standard_responses_audience'), table_name='standard_responses')
    op.drop_table('standard_responses')
    op.drop_index(op.f('ix_commands_title'), table_name='commands')
    op.drop_index(op.f('ix_commands_system'), table_name='commands')
    op.drop_index(op.f('ix_commands_id'), table_name='commands')
    op.drop_index(op.f('ix_commands_category'), table_name='commands')
    op.drop_table('commands')
    # ### end Alembic commands ###
