"""add_status_to_dept_and_location

Revision ID: 5412028969ec
Revises: 66716d60e9bd
Create Date: 2026-09-27 16:04:21.420836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5412028969ec'
down_revision: Union[str, None] = '66716d60e9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('status', sa.String(length=32), server_default='ativa', nullable=False))
    op.add_column('technical_locations', sa.Column('status', sa.String(length=32), server_default='ativa', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technical_locations', 'status')
    op.drop_column('departments', 'status')
    # ### end Alembic commands ###
