"""Add maintenance phase 9 fields

Revision ID: 62e9ff023792
Revises: 5412028969ec
Create Date: 2026-09-27 22:01:00.080818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e9ff023792'
down_revision: Union[str, None] = '5412028969ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_records', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('maintenance_records', sa.Column('technical_location_id', sa.Integer(), nullable=True))
    op.add_column('maintenance_records', sa.Column('attendance_id', sa.Integer(), nullable=True))
    op.add_column('maintenance_records', sa.Column('parts_used', sa.Text(), nullable=True))
    op.add_column('maintenance_records', sa.Column('otrs_ticket', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_maintenance_records_attendance_id'), 'maintenance_records', ['attendance_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_department_id'), 'maintenance_records', ['department_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_technical_location_id'), 'maintenance_records', ['technical_location_id'], unique=False)
    op.create_foreign_key(None, 'maintenance_records', 'technical_locations', ['technical_location_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'maintenance_records', 'attendances', ['attendance_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'maintenance_records', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'maintenance_records', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_records', type_='foreignkey')
    op.drop_constraint(None, 'maintenance_records', type_='foreignkey')
    op.drop_index(op.f('ix_maintenance_records_technical_location_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_department_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_attendance_id'), table_name='maintenance_records')
    op.drop_column('maintenance_records', 'otrs_ticket')
    op.drop_column('maintenance_records', 'parts_used')
    op.drop_column('maintenance_records', 'attendance_id')
    op.drop_column('maintenance_records', 'technical_location_id')
    op.drop_column('maintenance_records', 'department_id')
    # ### end Alembic commands ###
