"""add_account_email_to_license

Revision ID: 66716d60e9bd
Revises: 8846670ccf00
Create Date: 2026-09-27 15:43:53.743939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66716d60e9bd'
down_revision: Union[str, None] = '8846670ccf00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('licenses', sa.Column('account_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('licenses', 'account_email')
    # ### end Alembic commands ###
