"""make_attachment_entity_type_id_nullable

Revision ID: 7192eafe6bf3
Revises: 253c127af363
Create Date: 2026-10-02 11:53:48.585265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7192eafe6bf3'
down_revision: Union[str, None] = '253c127af363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachments', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('attachments', 'entity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_maintenance_equipment_equipment_id', table_name='maintenance_equipment')
    op.drop_index('ix_maintenance_equipment_maintenance_id', table_name='maintenance_equipment')
    op.drop_constraint('maintenance_records_equipment_id_fkey', 'maintenance_records', type_='foreignkey')
    op.create_foreign_key(None, 'maintenance_records', 'equipment', ['equipment_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'maintenance_records', type_='foreignkey')
    op.create_foreign_key('maintenance_records_equipment_id_fkey', 'maintenance_records', 'equipment', ['equipment_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_maintenance_equipment_maintenance_id', 'maintenance_equipment', ['maintenance_id'], unique=False)
    op.create_index('ix_maintenance_equipment_equipment_id', 'maintenance_equipment', ['equipment_id'], unique=False)
    op.alter_column('attachments', 'entity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attachments', 'entity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
