"""add technical_locations

Revision ID: 8846670ccf00
Revises: bfbe2617b9f9
Create Date: 2026-09-27 15:20:36.542528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8846670ccf00'
down_revision: Union[str, None] = 'bfbe2617b9f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technical_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location_type', sa.String(length=50), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_locations_department_id'), 'technical_locations', ['department_id'], unique=False)
    op.create_index(op.f('ix_technical_locations_id'), 'technical_locations', ['id'], unique=False)
    op.create_index(op.f('ix_technical_locations_store_id'), 'technical_locations', ['store_id'], unique=False)
    op.add_column('equipment', sa.Column('technical_location_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_equipment_technical_location_id'), 'equipment', ['technical_location_id'], unique=False)
    op.create_foreign_key(None, 'equipment', 'technical_locations', ['technical_location_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'equipment', type_='foreignkey')
    op.drop_index(op.f('ix_equipment_technical_location_id'), table_name='equipment')
    op.drop_column('equipment', 'technical_location_id')
    op.drop_index(op.f('ix_technical_locations_store_id'), table_name='technical_locations')
    op.drop_index(op.f('ix_technical_locations_id'), table_name='technical_locations')
    op.drop_index(op.f('ix_technical_locations_department_id'), table_name='technical_locations')
    op.drop_table('technical_locations')
    # ### end Alembic commands ###
