"""add is_active to checklist_templates

Revision ID: ae0d9c0f5b2b
Revises: e045d0dc8b1e
Create Date: 2026-09-28 00:51:01.233508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae0d9c0f5b2b'
down_revision: Union[str, None] = 'e045d0dc8b1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist_templates', sa.Column('is_active', sa.Boolean(), nullable=False, server_default="true"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklist_templates', 'is_active')
    # ### end Alembic commands ###
