"""add_projects_foundation

Revision ID: b3cb0736f865
Revises: ae0d9c0f5b2b
Create Date: 2026-09-28 01:59:36.680574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3cb0736f865'
down_revision: Union[str, None] = 'ae0d9c0f5b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_projects_store_id'), 'projects', ['store_id'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_table('project_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_notes_author_id'), 'project_notes', ['author_id'], unique=False)
    op.create_index(op.f('ix_project_notes_id'), 'project_notes', ['id'], unique=False)
    op.create_index(op.f('ix_project_notes_project_id'), 'project_notes', ['project_id'], unique=False)
    op.create_table('project_equipment',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'equipment_id')
    )
    op.add_column('attendances', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_attendances_project_id'), 'attendances', ['project_id'], unique=False)
    op.create_foreign_key(None, 'attendances', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.add_column('calendar_events', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_calendar_events_project_id'), 'calendar_events', ['project_id'], unique=False)
    op.create_foreign_key(None, 'calendar_events', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.add_column('checklists', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_checklists_project_id'), 'checklists', ['project_id'], unique=False)
    op.create_foreign_key(None, 'checklists', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.add_column('maintenance_records', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_maintenance_records_project_id'), 'maintenance_records', ['project_id'], unique=False)
    op.create_foreign_key(None, 'maintenance_records', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.add_column('stock_movements', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_stock_movements_project_id'), 'stock_movements', ['project_id'], unique=False)
    op.create_foreign_key(None, 'stock_movements', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.add_column('tasks', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('project_stage', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_column('tasks', 'project_stage')
    op.drop_column('tasks', 'project_id')
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_index(op.f('ix_stock_movements_project_id'), table_name='stock_movements')
    op.drop_column('stock_movements', 'project_id')
    op.drop_constraint(None, 'maintenance_records', type_='foreignkey')
    op.drop_index(op.f('ix_maintenance_records_project_id'), table_name='maintenance_records')
    op.drop_column('maintenance_records', 'project_id')
    op.drop_constraint(None, 'checklists', type_='foreignkey')
    op.drop_index(op.f('ix_checklists_project_id'), table_name='checklists')
    op.drop_column('checklists', 'project_id')
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.drop_index(op.f('ix_calendar_events_project_id'), table_name='calendar_events')
    op.drop_column('calendar_events', 'project_id')
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_index(op.f('ix_attendances_project_id'), table_name='attendances')
    op.drop_column('attendances', 'project_id')
    op.drop_table('project_equipment')
    op.drop_index(op.f('ix_project_notes_project_id'), table_name='project_notes')
    op.drop_index(op.f('ix_project_notes_id'), table_name='project_notes')
    op.drop_index(op.f('ix_project_notes_author_id'), table_name='project_notes')
    op.drop_table('project_notes')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_store_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
