"""feat(commands): support multi-step procedures

Revision ID: bfbe2617b9f9
Revises: b27185a17c87
Create Date: 2026-09-26 21:02:35.099337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfbe2617b9f9'
down_revision: Union[str, None] = 'b27185a17c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('command_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_steps_command_id'), 'command_steps', ['command_id'], unique=False)
    op.create_index(op.f('ix_command_steps_id'), 'command_steps', ['id'], unique=False)
    
    # --- Data Migration: Move existing commands into command_steps ---
    op.execute(
        "INSERT INTO command_steps (command_id, position, title, command_text) "
        "SELECT id, 1, 'Passo 1', command FROM commands WHERE command IS NOT NULL AND command != ''"
    )
    
    op.alter_column('commands', 'command',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- Data Migration Reverse: Restore the first step back to command ---
    op.execute(
        "UPDATE commands SET command = COALESCE((SELECT command_text FROM command_steps WHERE command_steps.command_id = commands.id AND command_steps.position = 1), '')"
    )
    
    op.alter_column('commands', 'command',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_command_steps_id'), table_name='command_steps')
    op.drop_index(op.f('ix_command_steps_command_id'), table_name='command_steps')
    op.drop_table('command_steps')
    # ### end Alembic commands ###
