"""add attendances and attendance_notes models

Revision ID: c62bbd6e354c
Revises: 4d6b319bf17a
Create Date: 2026-09-24 12:49:33.813056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c62bbd6e354c'
down_revision: Union[str, None] = '4d6b319bf17a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('otrs_ticket', sa.String(length=64), nullable=True),
    sa.Column('otrs_url', sa.String(length=512), nullable=True),
    sa.Column('requester_name', sa.String(length=255), nullable=True),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('equipment_name', sa.String(length=255), nullable=True),
    sa.Column('store_department', sa.String(length=255), nullable=True),
    sa.Column('problem_description', sa.Text(), nullable=True),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('cause', sa.Text(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('commands_used', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('knowledge_article_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_article_id'], ['knowledge_articles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['technician_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendances_id'), 'attendances', ['id'], unique=False)
    op.create_index(op.f('ix_attendances_otrs_ticket'), 'attendances', ['otrs_ticket'], unique=False)
    op.create_index(op.f('ix_attendances_status'), 'attendances', ['status'], unique=False)
    op.create_index(op.f('ix_attendances_technician_id'), 'attendances', ['technician_id'], unique=False)
    op.create_index(op.f('ix_attendances_title'), 'attendances', ['title'], unique=False)
    op.create_table('attendance_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attendance_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_notes_attendance_id'), 'attendance_notes', ['attendance_id'], unique=False)
    op.create_index(op.f('ix_attendance_notes_id'), 'attendance_notes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_notes_id'), table_name='attendance_notes')
    op.drop_index(op.f('ix_attendance_notes_attendance_id'), table_name='attendance_notes')
    op.drop_table('attendance_notes')
    op.drop_index(op.f('ix_attendances_title'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_technician_id'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_status'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_otrs_ticket'), table_name='attendances')
    op.drop_index(op.f('ix_attendances_id'), table_name='attendances')
    op.drop_table('attendances')
    # ### end Alembic commands ###
